### ISSUE TITLE
save buttons say "remove" in search page

### ISSUE THREAD

**Issue by jason741852** [jason741852/project276#36]

**Comment by afkewolczyk** [comment]
I tried to fix this and use the existing saving recipe function, and for some reason the save feature isn't working for me. Maybe this is just a local problem. @DontWorry33

**Comment by DontWorry33** [comment]
Save button works for me on itr3. try dropping and re-creating db maybe?

**Comment by afkewolczyk** [comment]
Yes, i had to drop the database whoops! 
The buttons say "remove" in the search page, but on the search page the remove function which is for the saved recipes page is also there. I just tried to fix it, but within the code of the save recipes function on the "home.html.erb" file, it calls on the array "foundItems" which is created dynamically. There doesnt seem to be an array to call on for the "search" page. I tried calling searchResults["hits"].each and just searchResults["hits"], and am unable to figure this out.

**Comment by DontWorry33** [comment]
I figured it out. I'll commit it soon

**Comment by DontWorry33** [comment]
potentially fixed. try and let me know if it worked. make sure you guys checkout the advanced_search branch as that's the one i committed it to

**Comment by afkewolczyk** [comment]
It works most of the time! Im not sure if we need to test it , but i tried searching "chicken" and saving a bunch of times, and sometimes got in the console "jquery.js:8625 POST http://localhost:5000/users/1/save_recipe 500 (Internal Server Error)" 
<img width="576" alt="screen shot 2016-11-30 at 11 10 12 pm" src="https://cloud.githubusercontent.com/assets/22460540/20785027/c9b05ac0-b752-11e6-89f4-487356672e07.png">

**Comment by DontWorry33** [comment]
Ahh good catch! I know what the problem is. I'll push it in a minute. Also it doesn't show if the recipe was saved already (supposed to say Saved if you already have it). I'll push both together

**Comment by DontWorry33** [comment]
Alright pushed the update. Please let me know if you get that error again or any others

**Comment by afkewolczyk** [comment]
I think a syntax error still here. 
<img width="1346" alt="screen shot 2016-12-02 at 9 24 43 pm" src="https://cloud.githubusercontent.com/assets/22460540/20857053/d18819fc-b8d5-11e6-9030-015b8f5e99c4.png">

**Comment by afkewolczyk** [comment]
I tried to save the ones in the far right column

**Comment by DontWorry33** [comment]
On it! nice catch again

**Comment by DontWorry33** [comment]
So it turned out to not be related to the column but the fact that I didn't escape the quote characters when getting the JSON representation of the string. Fixed

**Comment by afkewolczyk** [comment]
Looks really good hussain. awesome work.
